on:
    push:
        branches: 
            - master
        paths:
            - content/**.yml

name: Deploy Content


jobs:
    update-db:
        
        env: # Or as an environment variable
            SECRETS: ${{ secrets.SECRETS }}
            
        runs-on: [ubuntu-latest]
        
        container:
            image: python:3.7
            
        steps:
            
            - name: checkout
              uses: actions/checkout@v2
              
            - name: setup requirements
              run: python -m pip install -r requirements.txt
              
            - name: Deploy Content
              run: python scripts/update_database.py 